### ISSUE TITLE
您好，请问这个插件有FIS版的吗？

### ISSUE THREAD

**Issue by hello-lizhihua** [PeterMu/gulp-htmltojs#1]
我现在想在FIS中使用类似的编译功能，如何使用呢？

**Comment by PeterMu** [comment]
@dear-lizhihua 你用的 fis 哪个版本？fis2 还是 fis3 ？

**Comment by hello-lizhihua** [comment]
我用的是FIS3，昨天自己试着写FIS插件，用了您写的替换字符串的方法，最终转出来的结果有一些空格，希望能够去掉。

<pre>
    <code>
    define(function(require){ return '&lt;div&gt;  &lt;h1&gt;Hello World!&lt;h1&gt;&lt;/div&gt;'})
    </code>
</pre>

自己写的方法，很简陋，见笑。

<pre>
module.exports = function(content, file, settings) {
    content = content.toString();
    content = content.replace(/[\r\n]/g,"");
    //content = content.replace(/\"/g,"\\\"");
    content = content.replace(/\'/g,"\\'");
    content = content.trim();
    return 'define(function(){return \'' + content + '\'});';
};
</pre>

**Comment by PeterMu** [comment]
已修改，在转换时去除多余空格，看下index.js，感谢反馈！

dear-lizhihua notifications@github.com于2015年10月20日 周二16:39写道：
